### ISSUE TITLE
Call to nonexistent function Gdip_Startup()

### ISSUE THREAD

**Issue by gr4viton** [leoxiong-zzz/windowgrid#1]
On startup in 
ahk Version 1.0.48.05
Windows 7 Proffesional

Cannot start with error:

"Call to nonexistent function.
Specifically: Grid_Startup()"
...
"Line 019: pToken := Gdip_Startup()"
...

Do you think you can help me? Is it about the version or OS?

**Comment by gr4viton** [comment]
oh I needed to uncomment the include Gdip.ahk direction and download it

"
#Include Gdip.ahk
"
http://www.autohotkey.net/~tic/Gdip.ahk

**Comment by CanadianJeff** [comment]
why not just include this in the main????
